package com.homeofcode.wgkeyman;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Manages the WireGuard peer configuration for authorized users. Users authenticate via OAuth
 * (the {@code /wg} flow) and supply a WireGuard public key; this service validates the key,
 * generates the client config, persists the peer to the peers file, and reloads the live
 * interface.
 */
@Service
public class WireguardService {

    private final WgKeymanConfig config;

    // Track peers (CN -> public key) for the WireGuard config
    private final Map<String, String> peers = new LinkedHashMap<>();

    // @Autowired marks this as the constructor Spring uses (the class has a second, CLI-only
    // constructor; without this annotation Spring cannot choose between them).
    @Autowired
    public WireguardService(WgKeymanConfig config) {
        this(config, true);
    }

    /**
     * @param syncOnStartup whether to reload the live WireGuard interface immediately. The web
     *        server passes {@code true} so the running interface reflects the persisted peers.
     *        The admin CLI passes {@code false} so read-only commands (e.g. {@code peer list},
     *        {@code generate}) never touch the live interface.
     */
    public WireguardService(WgKeymanConfig config, boolean syncOnStartup) {
        this.config = config;
        loadPeers();
        if (syncOnStartup) {
            syncWireguardConfig();
        }
    }

    /**
     * Return the currently-tracked wg-keyman managed peers (CN -&gt; public key), in file order.
     */
    public Map<String, String> listPeers() {
        return new LinkedHashMap<>(peers);
    }

    /**
     * Remove a managed peer by CN. Returns {@code true} if a peer was removed (the caller should
     * then call {@link #save()} to persist and sync), {@code false} if no such peer existed.
     */
    public boolean removePeer(String cn) {
        return peers.remove(cn) != null;
    }

    /** Persist the current peers to the peers file and sync WireGuard. Returns a warning or null. */
    public String save() {
        return savePeers();
    }

    /** Reload the live WireGuard interface from the peers file. Returns a warning or null. */
    public String sync() {
        return syncWireguardConfig();
    }

    private static final String WG_KEYMAN_MARKER = "# Generated by wg-keyman";

    private Path getPeersPath() {
        return Path.of(config.getPeersFile());
    }

    // Stores manually-added peer sections (not managed by wg-keyman)
    private final List<String> manualPeerSections = new ArrayList<>();

    private void loadPeers() {
        Path path = getPeersPath();
        if (!Files.exists(path)) {
            return;
        }
        try {
            List<String> lines = Files.readAllLines(path);
            StringBuilder currentSection = new StringBuilder();
            boolean inPeerSection = false;
            boolean isWgKeymanManaged = false;
            String currentCn = null;

            for (String line : lines) {
                String trimmed = line.trim();

                if (trimmed.equals("[Peer]")) {
                    // Save previous section if it was manual
                    if (inPeerSection && !isWgKeymanManaged && currentSection.length() > 0) {
                        manualPeerSections.add(currentSection.toString());
                    }
                    // Start new section
                    currentSection = new StringBuilder();
                    currentSection.append(line).append("\n");
                    inPeerSection = true;
                    isWgKeymanManaged = false;
                    currentCn = null;
                } else if (inPeerSection) {
                    currentSection.append(line).append("\n");

                    if (trimmed.startsWith(WG_KEYMAN_MARKER)) {
                        isWgKeymanManaged = true;
                    } else if (trimmed.startsWith("# ") && trimmed.contains("@") && isWgKeymanManaged) {
                        // CN line for wg-keyman managed peer
                        currentCn = trimmed.substring(2).trim();
                    } else if (trimmed.startsWith("PublicKey = ") && currentCn != null) {
                        String publicKey = trimmed.substring("PublicKey = ".length()).trim();
                        peers.put(currentCn, publicKey);
                        currentCn = null;
                    }
                } else {
                    // Lines before any [Peer] section (header comments, etc.)
                    if (!trimmed.isEmpty()) {
                        // Store as part of manual content at the start
                        if (manualPeerSections.isEmpty() || !manualPeerSections.get(0).startsWith("[Peer]")) {
                            if (manualPeerSections.isEmpty()) {
                                manualPeerSections.add(line + "\n");
                            } else {
                                manualPeerSections.set(0, manualPeerSections.get(0) + line + "\n");
                            }
                        }
                    }
                }
            }

            // Don't forget the last section
            if (inPeerSection && !isWgKeymanManaged && currentSection.length() > 0) {
                manualPeerSections.add(currentSection.toString());
            }
        } catch (IOException e) {
            System.err.println("Warning: Could not load peers from " + path + ": " + e.getMessage());
        }
    }

    /**
     * Save peers to config file and sync WireGuard.
     * Preserves any peer sections that were not generated by wg-keyman.
     * @return warning message if there was a problem, null if successful
     */
    private synchronized String savePeers() {
        Path path = getPeersPath();

        // Backup old config if it exists
        backupOldConfig(path);

        // Build new peers config
        StringBuilder sb = new StringBuilder();

        // First, write any manual peer sections (preserving non-wg-keyman managed peers)
        for (String section : manualPeerSections) {
            sb.append(section);
            if (!section.endsWith("\n\n")) {
                sb.append("\n");
            }
        }

        // Then write wg-keyman managed peers
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
        for (var entry : peers.entrySet()) {
            String cn = entry.getKey();
            String publicKey = entry.getValue();
            Integer hostNumber = config.getUserHostNumbers().get(cn);
            if (hostNumber != null) {
                String allowedIps = config.getClientAddress(hostNumber);
                sb.append("[Peer]\n");
                sb.append(WG_KEYMAN_MARKER).append(" on ").append(timestamp).append("\n");
                sb.append("# ").append(cn).append("\n");
                sb.append("PublicKey = ").append(publicKey).append("\n");
                sb.append("AllowedIPs = ").append(allowedIps).append("\n");
                sb.append("\n");
            }
        }
        try {
            Files.writeString(path, sb.toString());
            System.out.println("Saved peers config to " + path);

            // Sync WireGuard config
            return syncWireguardConfig();
        } catch (IOException e) {
            String warning = "Could not save peers config: " + e.getMessage();
            System.err.println("Warning: " + warning);
            return warning;
        }
    }

    /**
     * Backup the old peers config file by appending .old extension.
     * The old entries are commented out with a timestamp.
     */
    private void backupOldConfig(Path path) {
        if (!Files.exists(path)) {
            return;
        }
        try {
            Path oldPath = Path.of(path.toString() + ".old");
            String timestamp = LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);

            // Read old config and comment it out
            String oldContent = Files.readString(path);
            StringBuilder backup = new StringBuilder();

            // Add header with timestamp
            backup.append("# Archived on ").append(timestamp).append("\n");

            // Comment out each line
            for (String line : oldContent.split("\n")) {
                if (!line.startsWith("#")) {
                    backup.append("# ");
                }
                backup.append(line).append("\n");
            }
            backup.append("\n");

            // Append to .old file (or create if doesn't exist)
            if (Files.exists(oldPath)) {
                String existingBackup = Files.readString(oldPath);
                backup.insert(0, existingBackup);
            }
            Files.writeString(oldPath, backup.toString());
            System.out.println("Backed up old config to " + oldPath);
        } catch (IOException e) {
            System.err.println("Warning: Could not backup old config: " + e.getMessage());
        }
    }

    /**
     * Sync the WireGuard configuration using systemd.
     * Uses 'sudo systemctl reload wg-quick@<interface>' by default.
     * @return warning message if there was a problem, null if successful
     */
    private String syncWireguardConfig() {
        String syncCommand = config.getSyncCommand();
        String wgInterface = config.getWgInterface();

        // If no custom sync command, use systemd to reload WireGuard
        String[] command;
        if (syncCommand == null || syncCommand.trim().isEmpty()) {
            command = new String[]{"sudo", "-n", "systemctl", "reload", "wg-quick@" + wgInterface};
        } else {
            // Custom command - split by spaces (simple parsing)
            command = syncCommand.split("\\s+");
        }

        try {
            System.out.println("Running: " + String.join(" ", command));
            ProcessBuilder pb = new ProcessBuilder(command);
            pb.redirectErrorStream(true);
            Process process = pb.start();

            // Read output
            StringBuilder output = new StringBuilder();
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    System.out.println("wg: " + line);
                    output.append(line).append("\n");
                }
            }

            int exitCode = process.waitFor();
            if (exitCode == 0) {
                System.out.println("WireGuard config synced successfully");
                return null;
            } else {
                String warning = "WireGuard sync command failed (exit code " + exitCode + ")";
                if (output.length() > 0) {
                    warning += ": " + output.toString().trim();
                }
                System.err.println("Warning: " + warning);
                return warning;
            }
        } catch (IOException e) {
            String warning = "Could not run WireGuard sync command: " + e.getMessage();
            System.err.println("Warning: " + warning);
            return warning;
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            String warning = "WireGuard sync command was interrupted";
            System.err.println("Warning: " + warning);
            return warning;
        }
    }

    /**
     * Check if the CN is in the authorized users list.
     */
    public boolean isAuthorizedUser(String cn) {
        return config.getUserHostNumbers().containsKey(cn);
    }

    /**
     * Get the host number for a user.
     */
    public Integer getHostNumber(String cn) {
        return config.getUserHostNumbers().get(cn);
    }

    /**
     * Generate the wireguard configuration for a client.
     */
    public String generateWireguardConfig(String cn, String clientPublicKey) {
        Integer hostNumber = getHostNumber(cn);
        if (hostNumber == null) {
            throw new IllegalArgumentException("User not found: " + cn);
        }

        String clientAddress = config.getClientAddress(hostNumber);

        StringBuilder config = new StringBuilder();
        config.append("[Interface]\n");
        config.append("# Add your private key below\n");
        config.append("# PrivateKey = <YOUR_PRIVATE_KEY>\n");
        config.append("Address = ").append(clientAddress).append("\n");
        config.append("\n");
        config.append("[Peer]\n");
        config.append("PublicKey = ").append(this.config.getServerPublicKey()).append("\n");
        config.append("Endpoint = ").append(this.config.getServerEndpoint()).append("\n");
        config.append("AllowedIPs = ").append(this.config.getAllowedIps()).append("\n");
        config.append("PersistentKeepalive = 25\n");

        return config.toString();
    }

    /**
     * Validate that a string is a valid WireGuard public key.
     * A valid key is a 32-byte Curve25519 public key, base64-encoded (44 characters ending with =).
     * @return null if valid, error message if invalid
     */
    public String validateWireguardPublicKey(String publicKey) {
        if (publicKey == null || publicKey.trim().isEmpty()) {
            return "Public key is required";
        }
        publicKey = publicKey.trim();

        // WireGuard public keys are exactly 44 characters (32 bytes base64-encoded)
        if (publicKey.length() != 44) {
            return "Invalid WireGuard public key: must be exactly 44 characters";
        }

        // Must end with = (32 bytes = 256 bits, base64 encodes to 43 chars + 1 padding)
        if (!publicKey.endsWith("=")) {
            return "Invalid WireGuard public key: must end with '='";
        }

        // Validate base64 format and decode
        try {
            byte[] decoded = Base64.getDecoder().decode(publicKey);
            if (decoded.length != 32) {
                return "Invalid WireGuard public key: must decode to exactly 32 bytes";
            }
        } catch (IllegalArgumentException e) {
            return "Invalid WireGuard public key: not valid base64";
        }

        return null; // Valid
    }

    /**
     * Process a public key for an OAuth-authenticated user.
     * This is used by the /wg endpoint where the user is authenticated via OAuth
     * and supplies their public key directly.
     */
    public WireguardResult processPublicKey(String email, String publicKey) {
        // Check authorization
        if (!isAuthorizedUser(email)) {
            return WireguardResult.error("User '" + email + "' is not authorized");
        }

        // Validate public key format
        String validationError = validateWireguardPublicKey(publicKey);
        if (validationError != null) {
            return WireguardResult.error(validationError);
        }
        publicKey = publicKey.trim();

        // Generate config
        String wgConfig = generateWireguardConfig(email, publicKey);

        // Update the WireGuard peers config with the new public key
        peers.put(email, publicKey);
        String warning = savePeers();

        if (warning != null) {
            return WireguardResult.successWithWarning(email, publicKey, wgConfig, warning);
        }
        return WireguardResult.success(email, publicKey, wgConfig);
    }

    /**
     * Result of processing a WireGuard public key submission.
     */
    public record WireguardResult(
            boolean valid,
            String errorMessage,
            String warningMessage,
            String commonName,
            String wireguardPublicKey,
            String wireguardConfig
    ) {
        public static WireguardResult error(String message) {
            return new WireguardResult(false, message, null, null, null, null);
        }

        public static WireguardResult success(String cn, String wgPublicKey, String wgConfig) {
            return new WireguardResult(true, null, null, cn, wgPublicKey, wgConfig);
        }

        public static WireguardResult successWithWarning(String cn, String wgPublicKey, String wgConfig, String warning) {
            return new WireguardResult(true, null, warning, cn, wgPublicKey, wgConfig);
        }
    }
}
