server.port=9876
wgmgr.server=10.0.0.1
wgmgr.network=10.0.0.0/24
wgmgr.server-endpoint=vpn.example.com:51820
wgmgr.server-public-key=+PEFSJuaUuYWFeVQGmJNo8e1MRrRLmWJq7Bd3m/lFEg=
wgmgr.ca-cert=ca.crt
wgmgr.users-file=users.lst
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB
