package com.homeofcode.wgkeyman.cli;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Base64;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration tests for the admin CLI. These build a throwaway configuration (users.lst,
 * peers.conf, application.properties) in a temp dir, point {@code spring.config.location} at it,
 * and drive {@link AdminCli#run(String[])} directly.
 */
class AdminCliTest {

    private static final String VALID_WG_KEY = Base64.getEncoder().encodeToString(new byte[32]); // 44 chars, ends '='

    @TempDir
    Path tempDir;

    private PrintStream originalOut;
    private ByteArrayOutputStream captured;
    private String previousConfigLocation;

    @BeforeEach
    void setUp() throws Exception {
        Files.writeString(tempDir.resolve("users.lst"), "5 test@example.com\n10 admin@example.com\n");
        Files.writeString(tempDir.resolve("peers.conf"), "");

        Path props = tempDir.resolve("application.properties");
        Files.writeString(props, String.join("\n",
                "wgmgr.server=10.0.0.1",
                "wgmgr.network=10.0.0.0/24",
                "wgmgr.server-endpoint=vpn.example.com:51820",
                "wgmgr.server-public-key=" + VALID_WG_KEY,
                "wgmgr.users-file=" + tempDir.resolve("users.lst"),
                "wgmgr.peers-file=" + tempDir.resolve("peers.conf"),
                "wgmgr.sync-command=echo synced",
                ""));

        previousConfigLocation = System.getProperty("spring.config.location");
        System.setProperty("spring.config.location", props.toString());

        originalOut = System.out;
        captured = new ByteArrayOutputStream();
        System.setOut(new PrintStream(captured, true, StandardCharsets.UTF_8));
    }

    @AfterEach
    void tearDown() {
        System.setOut(originalOut);
        if (previousConfigLocation == null) {
            System.clearProperty("spring.config.location");
        } else {
            System.setProperty("spring.config.location", previousConfigLocation);
        }
    }

    private String stdout() {
        return captured.toString(StandardCharsets.UTF_8);
    }

    @Test
    void userListShowsConfiguredUsers() {
        assertEquals(0, AdminCli.run(new String[]{"user", "list"}));
        String out = stdout();
        assertTrue(out.contains("test@example.com"), out);
        assertTrue(out.contains("admin@example.com"), out);
    }

    @Test
    void userAddThenListIncludesNewUser() {
        assertEquals(0, AdminCli.run(new String[]{"user", "add", "20", "new@example.com"}));
        captured.reset();
        assertEquals(0, AdminCli.run(new String[]{"user", "list"}));
        assertTrue(stdout().contains("new@example.com"));
    }

    @Test
    void userAddDuplicateFails() {
        assertEquals(1, AdminCli.run(new String[]{"user", "add", "99", "test@example.com"}));
    }

    @Test
    void userRemoveDropsUser() {
        assertEquals(0, AdminCli.run(new String[]{"user", "remove", "admin@example.com"}));
        captured.reset();
        AdminCli.run(new String[]{"user", "list"});
        assertFalse(stdout().contains("admin@example.com"));
    }

    @Test
    void generateUsesRegisteredKey() throws Exception {
        // Pre-register a managed peer for the user so generate has a key to look up.
        Files.writeString(tempDir.resolve("peers.conf"),
                "[Peer]\n# Generated by wg-keyman on 2026-01-01T00:00:00\n# test@example.com\n"
                        + "PublicKey = " + VALID_WG_KEY + "\nAllowedIPs = 10.0.0.5/32\n");

        assertEquals(0, AdminCli.run(new String[]{"generate", "test@example.com"}));
        String out = stdout();
        assertTrue(out.contains("[Interface]"), out);
        assertTrue(out.contains("Address = 10.0.0.5/32"), out);
    }

    @Test
    void generateRejectsUnauthorizedUser() {
        assertEquals(1, AdminCli.run(new String[]{"generate", "nobody@example.com"}));
    }

    @Test
    void generateFailsWhenNoKeyRegistered() {
        // admin@example.com is authorized but has no registered peer key (peers.conf is empty).
        assertEquals(1, AdminCli.run(new String[]{"generate", "admin@example.com"}));
    }

    @Test
    void generateRequiresCnArgument() {
        assertEquals(2, AdminCli.run(new String[]{"generate"}));
    }

    @Test
    void peerListEmptyByDefault() {
        assertEquals(0, AdminCli.run(new String[]{"peer", "list"}));
        assertTrue(stdout().contains("no managed peers"));
    }

    @Test
    void peerSyncRebuildsAndReloads() throws Exception {
        // peers.conf starts present-but-empty in setUp; sync should rebuild it and reload.
        assertEquals(0, AdminCli.run(new String[]{"peer", "sync"}));
        assertTrue(stdout().contains("Rebuilt peers file"));
        assertTrue(Files.exists(tempDir.resolve("peers.conf")));
    }

    @Test
    void unknownSubcommandReturnsUsageError() {
        assertEquals(2, AdminCli.run(new String[]{"bogus"}));
    }

    @Test
    void noArgumentsPrintsHelp() {
        assertEquals(0, AdminCli.run(new String[]{}));
        String out = stdout();
        assertTrue(out.contains("Usage:"), out);
        assertTrue(out.contains("user"), out);
        assertTrue(out.contains("peer"), out);
        assertTrue(out.contains("generate"), out);
    }
}
